#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

force_load fat
force_load vfat
force_load nls_ascii
force_load nls_cp437
force_load nls_utf8
