#!/bin/sh

set -eu

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
	remove|purge|upgrade|disappear)
		if [ -e /sbin/start-stop-daemon.chroot-disable-services-original ] ; then
			mv /sbin/start-stop-daemon.chroot-disable-services-original /sbin/start-stop-daemon
		fi
	;;

	abort-install|abort-upgrade|failed-upgrade)
	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
esac

exit 0
