#!/bin/sh

set -eu

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
	install|upgrade)
		if [ -e /sbin/start-stop-daemon ] ; then
			mv /sbin/start-stop-daemon /sbin/start-stop-daemon.chroot-disable-services-original
		fi
	;;

	abort-upgrade)
	;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
esac

exit 0
