#!/bin/sh -eu

PREREQ=""
prereqs()
{
	echo "${PREREQ}"
}

case "${1:-}" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

rootfs_overlay_size="256m"
rootfs_overlay_copy=0

for arg in $(cat /proc/cmdline) ; do
	case $arg in
	rootfs-overlay-size=*)
		rootfs_overlay_size=${arg#rootfs-overlay-size=}
		;;
	rootfs-overlay-copy=1)
		rootfs_overlay_copy=1
		;;
	esac
done

mkdir -p /mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to create overlay tmpfs mount point"
mount -t tmpfs -o mode=0700,size="$rootfs_overlay_size" tmpfs /mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to mount tmpfs"
mkdir /mnt/rootfs-overlay/lower && mkdir /mnt/rootfs-overlay/upper && mkdir /mnt/rootfs-overlay/work \
	|| panic "ERROR: rootfs-overlay failed to create overlay mount points"

if [ $rootfs_overlay_copy -eq 0 ] ; then
	# move existing root mount (boot medium)
	mkdir -p /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to create mount point for boot medium"
	mount -o remount,ro ${rootmnt} \
		|| panic "ERROR: rootfs-overlay failed to remount ${rootmnt} read-only"
	mount --move ${rootmnt} /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to move ${rootmnt}"

	# mount squashfs on lowerdir
	mount -o loop,ro /mnt/rootfs-overlay/boot/root.squashfs /mnt/rootfs-overlay/lower \
		|| panic "ERROR: rootfs-overlay failed to loop mount root squashfs in overlay lowerdir"
fi

if [ $rootfs_overlay_copy -eq 1 ] ; then
	# mount new tmpfs to copy contents of boot medium into
	mkdir /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to create boot medium tmpfs mountpoint"
	mount -t tmpfs -o mode=0700 tmpfs /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to mount boot medium tmpfs"

	# copy root squashfs file to boot medium tmpfs, unmount root device, and loop
	# mount the copied squashfs file
	log_begin_msg "rootfs-overlay copying root filesystem to memory ... "
	cp ${rootmnt}/root.squashfs /mnt/rootfs-overlay/boot/ \
		|| panic "ERROR: rootfs-overlay failed to copy ${rootmnt}/root.squashfs"
	if [ -f ${rootmnt}/rootfs-overlay.tar.gz ] ; then
		cp ${rootmnt}/rootfs-overlay.tar.gz /mnt/rootfs-overlay/boot/ \
			|| panic "ERROR: rootfs-overlay failed to copy ${rootmnt}/root.squashfs"
	fi
	log_end_msg
	umount ${rootmnt} \
		|| panic "ERROR: rootfs-overlay failed to unmount ${rootmnt}"
	mount -o loop,ro /mnt/rootfs-overlay/boot/root.squashfs /mnt/rootfs-overlay/lower \
		|| panic "ERROR: rootfs-overlay failed to loop mount root block device copy from boot medium tmpfs"

	# remount boot medium tmpfs read-only
	mount -o remount,ro /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to remount boot medium tmpfs read-only"

	# try to shrink boot medium tmpfs
	blocks_total=$(stat -c %b -f /mnt/rootfs-overlay/boot)
	blocks_free=$(stat -c %f -f /mnt/rootfs-overlay/boot)
	mount -o remount,nr_blocks=$(($blocks_total - $blocks_free)) /mnt/rootfs-overlay/boot
fi

# mount overlay as new rootfs
mount -t overlay overlay -o lowerdir=/mnt/rootfs-overlay/lower,upperdir=/mnt/rootfs-overlay/upper,workdir=/mnt/rootfs-overlay/work ${rootmnt} \
	|| panic "ERROR: rootfs-overlay failed to mount overlay"

# unpack overlay tarball
if [ -f /mnt/rootfs-overlay/boot/rootfs-overlay.tar.gz ] ; then
	tar -xzf /mnt/rootfs-overlay/boot/rootfs-overlay.tar.gz -C ${rootmnt} \
		|| panic "ERROR: rootfs-overlay failed to unpack overlay in ${rootmnt}"
fi

# move tmpfs backing the overlayfs into rootfs mountpoint
mkdir -p ${rootmnt}/mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to create overlay tmpfs mount point inside overlay"
mount --move /mnt/rootfs-overlay ${rootmnt}/mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to move overlay tmpfs into overlay"
