#!/bin/sh -eux

unmount()
{
	# unmount bind mounts created by build process
	for mount in "build.d/var/cache/apt/archives" "build.d/dev" "build.d/proc" "build.d/sys" ; do
		if mountpoint -q "$mount" ; then
			umount "$mount"
		fi
	done
}

# call and trap register unmount()
unmount
trap "unmount" EXIT INT

# create clean build.d from bootstrap.d
rm -rf --one-file-system build.d
cp -a --reflink=auto bootstrap.d build.d

# add apt mirror
echo "deb http://deb.debian.org/debian sid main contrib non-free" > build.d/etc/apt/sources.list

# copy include directory into build.d
cp -r build.include.d/* build.d/

# bind mount current system into build.d
mount --bind /dev build.d/dev
mount --bind /proc build.d/proc
mount --bind /sys build.d/sys
mount --bind /var/cache/apt/archives build.d/var/cache/apt/archives

# install chroot helper that disables service invocation
dpkg --root=build.d --install chroot-disable-services.deb

# call chroot build script with clean environment (to prevent locale issues, etc.)
cp -r build.chroot features.d/ build.d/
env --ignore-environment PATH="/usr/sbin:/usr/bin:/sbin:/bin" TERM="$TERM" USER="$USER" chroot build.d /build.chroot
rm -rf build.d/build.chroot build.d/features.d/

# remove chroot helper that disables service invocation
dpkg --root=build.d --purge chroot-disable-services

# unmount bind mounts
unmount
