#!/bin/sh -eux

# if build failed, directory may still be mounted
if mountpoint -q build.d/var/cache/apt/archives ; then
	umount build.d/var/cache/apt/archives
fi

rm -rf --one-file-system build.d
cp -a --reflink=auto bootstrap.d build.d

echo "deb http://deb.debian.org/debian sid main contrib non-free" > build.d/etc/apt/sources.list

cp -r build.include.d/* build.d/

#mount --bind /dev build.d/dev
#mount --bind /proc build.d/proc
#mount --bind /sys build.d/sys
mount --bind /var/cache/apt/archives build.d/var/cache/apt/archives

dpkg --root=build.d --install features.d/debimg-helper-policy-rc.d.deb
dpkg --root=build.d --install features.d/debimg-feature-*.deb

cp build.chroot build.d/
chroot build.d /build.chroot
rm build.d/build.chroot

dpkg --root=build.d --purge debimg-helper-policy-rc.d

sed -i 's/^KEYMAP=n/KEYMAP=y/' build.d/etc/initramfs-tools/initramfs.conf

#umount build.d/dev
#umount build.d/proc
#umount build.d/sys
umount build.d/var/cache/apt/archives

# cleanup
rm -rf --one-file-system build.d/var/cache/apt/*
rm -rf --one-file-system build.d/var/lib/apt/lists/*
rm -rf --one-file-system build.d/var/log/*
