#!/bin/sh -eux

unmount()
{
	# unmount bind mounts created by build process
	for mount in "build.d/var/cache/apt/archives" "build.d/dev" "build.d/proc" "build.d/sys" ; do
		if mountpoint -q "$mount" ; then
			umount "$mount"
		fi
	done
}

# call and trap register unmount()
unmount
trap "unmount" EXIT INT

# create clean build.d from bootstrap.d
rm -rf --one-file-system build.d
cp -a --reflink=auto bootstrap.d build.d

# add apt mirror
echo "deb http://deb.debian.org/debian sid main contrib non-free" > build.d/etc/apt/sources.list

# configure hostname
echo "live" > build.d/etc/hostname
cat > build.d/etc/hosts <<-EOF
	127.0.0.1 localhost
	127.0.1.1 live
EOF

# bind mount current system into build.d
mount --bind /dev build.d/dev
mount --bind /proc build.d/proc
mount --bind /sys build.d/sys
mount --bind /var/cache/apt/archives build.d/var/cache/apt/archives

# install rootfs-overlay package (handles overlayfs setup via initramfs scripts)
dpkg --root=build.d --install rootfs-overlay.deb

# call chroot build script with clean environment (to prevent locale issues, etc.)
cp build.chroot build.d/
env --ignore-environment PATH="/usr/sbin:/usr/bin:/sbin:/bin" TERM="$TERM" USER="$USER" chroot build.d /build.chroot
rm -rf build.d/build.chroot build.d/features.d/

# remove cdebootstrap helper that disables service invocation
dpkg --root=build.d --purge cdebootstrap-helper-rc.d

# unmount bind mounts
unmount
