#!/bin/sh -eu

PREREQ=""
prereqs()
{
	echo "${PREREQ}"
}

case "${1:-}" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

rootfs_overlay=0

for arg in $(cat /proc/cmdline) ; do
	case $arg in
	rootfs-overlay=0)
		# disabled
		rootfs_overlay=0
		;;
	rootfs-overlay=1)
		# mount squashfs directly (boot medium is not unpluggable)
		rootfs_overlay=1
		;;
	rootfs-overlay=2)
		# copy squashfs image to tmpfs (boot medium is unpluggable)
		rootfs_overlay=2
		;;
	rootfs-overlay=*)
		log_warning_msg "Invalid rootfs-overlay parameter: $arg"
		;;
	esac
done

# exit immediately if rootfs-overlay has not been enabled
if [ $rootfs_overlay -eq 0 ] ; then
	exit 0
fi

# create overlay mountpoint and mount backing tmpfs
mkdir -p /mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to create overlay tmpfs mount point"
mount -t tmpfs -o mode=0700 tmpfs /mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to mount tmpfs"
mkdir /mnt/rootfs-overlay/lower && mkdir /mnt/rootfs-overlay/upper && mkdir /mnt/rootfs-overlay/work \
	|| panic "ERROR: rootfs-overlay failed to create overlay mount points"

# unpack overlay tarball
if [ -f ${rootmnt}/rootfs-overlay.tar.gz ] ; then
	tar -xzf ${rootmnt}/rootfs-overlay.tar.gz -C /mnt/rootfs-overlay/upper \
		|| panic "ERROR: rootfs-overlay failed to unpack overlay tarball in overlay upperdir"
fi

# mount squashfs directly (boot medium is not unpluggable)
if [ $rootfs_overlay -eq 1 ] ; then
	# move existing root mount (boot medium)
	mkdir -p /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to create mount point for boot medium"
	mount -o remount,ro ${rootmnt} \
		|| panic "ERROR: rootfs-overlay failed to remount ${rootmnt} read-only"
	mount --move ${rootmnt} /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to move ${rootmnt}"
fi

# copy squashfs image to tmpfs (boot medium is unpluggable)
if [ $rootfs_overlay -eq 2 ] ; then
	# create directory for squashfs file
	mkdir -p /mnt/rootfs-overlay/boot && chmod 500 /mnt/rootfs-overlay/boot \
		|| panic "ERROR: rootfs-overlay failed to create directory for filesystem image"

	# copy root squashfs file to boot medium tmpfs
	log_begin_msg "rootfs-overlay copying root filesystem image to memory ... "
	cp ${rootmnt}/rootfs.squashfs /mnt/rootfs-overlay/boot/ &&
	chmod 400 /mnt/rootfs-overlay/boot/rootfs.squashfs \
		|| panic "ERROR: rootfs-overlay failed to copy ${rootmnt}/rootfs.squashfs"
	log_end_msg

	# unmount root device
	umount ${rootmnt} \
		|| panic "ERROR: rootfs-overlay failed to unmount ${rootmnt}"
fi

# loop mount squashfs on lowerdir
mount -o loop,ro /mnt/rootfs-overlay/boot/rootfs.squashfs /mnt/rootfs-overlay/lower \
	|| panic "ERROR: rootfs-overlay failed to loop mount root squashfs in overlay lowerdir"

# mount overlay as new rootfs
mount -t overlay overlay -o lowerdir=/mnt/rootfs-overlay/lower,upperdir=/mnt/rootfs-overlay/upper,workdir=/mnt/rootfs-overlay/work ${rootmnt} \
	|| panic "ERROR: rootfs-overlay failed to mount overlay"

# move tmpfs backing the overlayfs into rootfs mountpoint
mkdir -p ${rootmnt}/mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to create overlay tmpfs mount point inside overlay"
mount --move /mnt/rootfs-overlay ${rootmnt}/mnt/rootfs-overlay \
	|| panic "ERROR: rootfs-overlay failed to move overlay tmpfs into overlay"
