#!/bin/sh -eu

. /etc/os-release
ESP=$(bootctl --print-esp-path)
BOOT=$(bootctl --print-boot-path)
MACHINE_ID=$(cat /etc/machine-id)
BOOT_OPTIONS=$(cat /etc/kernel/cmdline)

# bootctl update always copies its .efi files, so only run it if files differ
# TODO: replace with dpkg trigger: https://stackoverflow.com/q/15276535
# FIXME: x86-64 specific workaround
if ! cmp /usr/lib/systemd/boot/efi/systemd-bootx64.efi $ESP/EFI/systemd/systemd-bootx64.efi ; then
	bootctl update
fi

if [ ! -d $BOOT/$MACHINE_ID/ ] ; then
	mkdir $BOOT/$MACHINE_ID/
fi

installed_versions=""
for kernel_path in /boot/vmlinu?-* ; do
	[ -e "$kernel_path" ] || continue

	kernel=${kernel_path##*/}
	version=${kernel##vmlinu?-}
	initrd=initrd.img-$version

	installed_versions="$installed_versions $version"

	if [ ! -d $BOOT/$MACHINE_ID/$version/ ] ; then
		mkdir $BOOT/$MACHINE_ID/$version/
	fi

	# only copy if file contents have changed (comparison by timestamp is
	# error prone, because $BOOT is likely FAT32, which may have different
	# timestamp precision than /boot)
	if ! cmp --quiet /boot/$kernel $BOOT/$MACHINE_ID/$version/linux ; then
		cp -v /boot/$kernel $BOOT/$MACHINE_ID/$version/linux
	fi
	if [ -f /boot/$initrd ] ; then
		if ! cmp --quiet /boot/$initrd $BOOT/$MACHINE_ID/$version/initrd ; then
			cp -v /boot/$initrd $BOOT/$MACHINE_ID/$version/initrd
		fi
	fi

	CONF_NEW="\
title   $PRETTY_NAME (Linux $version)
options $BOOT_OPTIONS
linux   /$MACHINE_ID/$version/linux"
	if [ -f /boot/$initrd ] ; then
		CONF_NEW="$CONF_NEW\ninitrd  /$MACHINE_ID/$version/initrd"
	fi

	# write config file if necessary
	if [ -e $BOOT/loader/entries/$MACHINE_ID-$version.conf ] ; then
		CONF_OLD=$(cat $BOOT/loader/entries/$MACHINE_ID-$version.conf)
	fi
	if [ "${CONF_OLD:-}" != "$CONF_NEW" ] ; then
		echo "$CONF_NEW" > $BOOT/loader/entries/$MACHINE_ID-$version.conf
	fi
done

# delete kernels that are not longer present in /boot
for version_dir in $BOOT/$MACHINE_ID/* ; do
	[ -d "$version_dir" ] || continue

	version=${version_dir##*/}
        if [ ! -z "${installed_versions##*$version*}" ] ; then
                rm -rfv $BOOT/$MACHINE_ID/$version/ $BOOT/loader/entries/$MACHINE_ID-$version.conf
        fi
done
