#!/bin/sh
# postinst script for update-systemd-boot

set -e

if [ "$1" = "new-preinst" ] ; then
	if ! bootctl is-installed ; then
		echo >&2 "update-systemd-boot: systemd-boot is not installed; install it via bootctl install first!"
	fi
fi
