#!/bin/sh -eux

# make apt-get not ask any questions
# https://manpages.debian.org/unstable/debconf-doc/debconf.7.en.html#Frontends
export DEBIAN_FRONTEND=noninteractive

# fetch repository index
apt-get update

# setup C locale as default
apt-get --assume-yes install locales
update-locale LANG=C.UTF-8

# install subset of important packages plus some personal favorites
apt-get --assume-yes --no-install-recommends -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
	bsdmainutils cpio dbus dmidecode init iproute2 iputils-ping \
	kmod mount nano netbase sensible-utils systemd systemd-sysv tzdata udev \
	vim-common vim-tiny

# install remaining packages
apt-get --assume-yes --no-install-recommends -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
	busybox console-setup keyboard-configuration linux-image-amd64 \
	\
	bash-completion file htop less man-db manpages psmisc screen sudo \
	pciutils usbutils \
	\
	iputils-ping iputils-tracepath netcat-openbsd rsync \
	\
	btrfs-progs \
	\
	openssh-server

# setup boot loader
bootctl --esp-path=/boot/efi install

# use systemd services
systemctl enable systemd-networkd.service
systemctl enable systemd-resolved.service
systemctl enable systemd-timesyncd.service

# use systemd-resolved's resolv.conf instead of the one generated by debootstrap
ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf

# set root password "root" (generate via `openssl passwd -1 -salt ""`)
usermod --password '$1$$oCLuEVgI1iAqOA8pwkzAg1' root
