#!/bin/sh

PREREQ=""
prereqs()
{
    echo "${PREREQ}"
}

case "$1" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

for arg in $(cat /proc/cmdline) ; do
	case $arg in
	configroot=*)
		arg=${arg#configroot=}

		mkdir /mnt/config || panic
		mount -o ro,showexec $arg /mnt/config || panic
		if [ -d /mnt/config/config/ ] ; then
			cp -r /mnt/config/config/* $rootmnt/ || panic
		fi

		umount /mnt/config || panic
		rmdir /mnt/config || panic

		break
		;;
	esac
done
